### ISSUE TITLE
Kitty Top Bar Removal

### ISSUE THREAD

**Issue by Cyrof** [Cyrof/dotfiles-i3#1]
## Removal of Kitty top bar

The Kitty terminal top bar should be removed if possible. Makes the terminal window nicer looking instead of constantly having a top bar with every kitty terminal instance.

**Comment by kovidgoyal** [comment]
hide_window_decorations yes

in kitty.conf

**Comment by Cyrof** [comment]
Hi @kovidgoyal, 

Thank you for taking the time to reply to this issue. I actually created it for personal reference as part of my dotfiles workflow. I didn't expect it to catch your attention😅. 

That said, I appreciate the insight you've shared.

I'll go ahead and implement this and close the issue when i have committed the changes, but thank you again for your time and support with Kitty. It's a fantastic tool that I really enjoy using. 

Best regards, 
@Cyrof

**Comment by Cyrof** [comment]
This issue is resolve in this commit ee658d500472b94725fd414ec36696daf768d838 and will now be closed.
